# Generated by Django 6.0 on 2026-02-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List_of_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('sla_hours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='division',
            name='division_code_0cf91a_idx',
        ),
        migrations.RemoveConstraint(
            model_name='division',
            name='unique_division_per_zone',
        ),
        migrations.RemoveConstraint(
            model_name='division',
            name='unique_division_code_per_zone',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='escalation_level',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='officer_role',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='subcategory',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_subcategory_per_category',
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_subcategory_code_per_category',
        ),
        migrations.RemoveIndex(
            model_name='zone',
            name='zone_code_6de348_idx',
        ),
        migrations.RemoveConstraint(
            model_name='zone',
            name='unique_zone_per_system',
        ),
        migrations.RemoveConstraint(
            model_name='zone',
            name='unique_zone_code_per_system',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_per_division',
        ),
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_department_code_per_division',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='responsible_unit',
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_resolver_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responsible_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_responsible_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_tickets', to='core.department'),
        ),
        migrations.AddField(
            model_name='list_of_issue',
            name='Issue_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
        migrations.AddField(
            model_name='list_of_issue',
            name='escalation_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.escalationlevel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.list_of_issue'),
        ),
        migrations.AddField(
            model_name='officer_role',
            name='officer_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='officer_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.officer_role'),
        ),
        migrations.RemoveField(
            model_name='division',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='responsible_unit',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='system',
        ),
        migrations.RemoveField(
            model_name='department',
            name='division',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='OfficerRole',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='System',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
    ]
