# Generated by Django 6.0 on 2026-02-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_list_of_issue_officer_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponsibleUnit',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_department',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_code_per_department',
        ),
        migrations.RemoveField(
            model_name='category',
            name='coach',
        ),
    ]
