# Generated by Django 6.0 on 2026-02-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_responsibleunit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_responsible_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_tickets', to='core.department'),
        ),
        migrations.CreateModel(
            name='Resolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_busy', models.BooleanField(default=False, help_text='Threshold 1: True if has active tickets')),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.list_of_issue')),
                ('officer_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.officer_role')),
                ('responsible_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue_resolver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.resolver'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
