# Generated by Django 6.0 on 2026-02-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_assigned_responsible_unit_resolver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_resolver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.resolver'),
        ),
    ]
